spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: sa
          password: ""
          schema: db/data-h2.sql
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver
        slave_1:
          username: sa
          password: ""
          schema: db/febs_base.sql
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver

