spring:
  session:
    store-type: jdbc
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/data-h2.sql
    username: test
    password: password
    url: jdbc:h2:mem:main;DB_CLOSE_ON_EXIT=FALSE
  
mybatis:
  type-aliases-package: app.entity
  mapper-locations:
  - mapper/*.xml
