spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/data-h2.sql
    username: test
    password: password
    url: jdbc:h2:mem:main
  
  thymeleaf:
    cache: false
  
mybatis:
  type-aliases-package: app.entity
  mapper-locations:
  - mapper/*.xml
