spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/db/mybatis;IGNORECASE=TRUE;MODE=MySQL
    username: admin
    password: 
    schema:
    - classpath:db/*.sql
    
  h2:
    console:
      enabled: true
      path: /h2
   
  thymeleaf:
    cache: false
    
mybatis:
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: app.entity
