spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: test
    password: test
    schema:
    - classpath:db/user.sql
    url: jdbc:h2:mem:main
    
  thymeleaf:
    cache: false
    
    
mybatis:
  type-aliases-package: app.entity
  mapper-locations:
  - mapper/*.xml
  